### Variáveis de ambiente
@baseUrl = http://localhost:8080
@contentType = application/json

### Criar uma transação de crédito
POST {{baseUrl}}/transactions
Content-Type: {{contentType}}

{
  "title": "Pagamento de salário",
  "amount": 3000.00,
  "type": "credit"
}

### Listar todas as transações
GET {{baseUrl}}/transactions
Content-Type: {{contentType}}


### Listar transações por id
GET {{baseUrl}}/transactions/4021ad66-959e-485a-9cba-451bb9a86ff4


### Obter resumo das transações (saldo total)
GET {{baseUrl}}/transactions/summary